Repository legend-exp/legend-pydataobj, pull requests merged in 2023-10, with the labels that each got.

#20 Vectorize `RadwareSigcompress`
  src/lgdo/compression/radware.py
  src/lgdo/compression/varlen.py
  tests/compression/test_radware_sigcompress.py
  tests/compression/test_uleb128_zigzag_diff.py
  tests/conftest.py
Labels: compression

#22 Turn Numba cache on for compression routines
  src/lgdo/compression/base.py
  src/lgdo/compression/radware.py
  src/lgdo/compression/varlen.py
Labels: enhancement

#26 fix incorrect culling message
  src/lgdo/lh5_store.py
Labels: bug
