Repository legend-exp/legend-pydataobj, pull requests merged in 2024-11, with the labels that each got.

#110 Updates to LH5Iterator and LH5Store to read huge number of files
  pyproject.toml
  src/lgdo/lh5/_serializers/read/ndarray.py
  src/lgdo/lh5/_serializers/read/scalar.py
  src/lgdo/lh5/_serializers/read/utils.py
  src/lgdo/lh5/_serializers/read/vector_of_vectors.py
  src/lgdo/lh5/iterator.py
  src/lgdo/lh5/store.py
  src/lgdo/lh5/utils.py
  src/lgdo/types/histogram.py
  src/lgdo/types/table.py
  src/lgdo/types/vectorofvectors.py
  tests/lh5/test_lh5_iterator.py
  tests/lh5/test_lh5_store.py
  tests/types/test_histogram.py
Labels: enhancement, performance

#120 Fix `read_as()` with file list of length 1
  src/lgdo/lh5/core.py
  src/lgdo/types/vectorofvectors.py
  tests/lh5/test_core.py
Labels: bug

#121 lh5concat: allow concatenating of group-like structs
  src/lgdo/cli.py
  tests/test_cli.py
Labels: enhancement, lh5

#116 Nested field mask
  src/lgdo/lh5/_serializers/read/composite.py
  src/lgdo/lh5/_serializers/read/utils.py
Labels: enhancement, lh5
