Repository legend-exp/legend-pydataobj, pull requests merged in 2024-02, with the labels that each got.

#67 Bugfix for varlen error msgs and specify nda in view_as "ak" so dtype correctly inferred
  README.md
  src/lgdo/compression/varlen.py
  src/lgdo/types/vectorofvectors.py
Labels: bug

#68 Add Patrick to CITATION.cff
  CITATION.cff
Labels: documentation

#70 `Table.view_as()` performance fixes
  src/lgdo/logging.py
  src/lgdo/types/array.py
  src/lgdo/types/table.py
Labels: bug, performance
